# Generated by Django 4.2.30 on 2026-06-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
